# Generated by Django 2.0.4 on 2018-05-14 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0007_remove_salon_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='staffer', verbose_name='Аватар')),
                ('phone', models.CharField(max_length=255, verbose_name='Сотовый')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес электронной почты')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Неизвестно'), (1, 'Мужской'), (2, 'Женский')], default=0, verbose_name='Пол')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.Salon')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
