# Generated by Django 2.0.4 on 2018-05-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='client', verbose_name='Аватар'),
        ),
    ]
