# Generated by Django 2.0.4 on 2018-05-18 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0007_remove_salon_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0002_auto_20180517_0318'),
        ('services', '0002_auto_20180517_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_changed', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('start', models.DateTimeField(verbose_name='Начало сеанса')),
                ('end', models.DateTimeField(verbose_name='Завершение сеанса')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.Salon', verbose_name='Клиент')),
                ('service_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceMasters', verbose_name='Услуга мастера')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
