# Generated by Django 2.0.4 on 2018-05-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_online',
            field=models.BooleanField(choices=[(True, 'Онлайн'), (False, 'Оффлайн')], default=False),
        ),
    ]
