# Generated by Django 2.0.4 on 2018-05-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetable_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='device_uid',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
    ]
