# Generated by Django 2.0.4 on 2018-04-23 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Должности',
                'verbose_name': 'Должность',
            },
        ),
        migrations.CreateModel(
            name='Staffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_changed', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='staffer', verbose_name='Аватар')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация')),
                ('master_fired', models.BooleanField(choices=[(True, 'Уволен'), (False, 'Работает')], default=False, verbose_name='Статус')),
                ('description', models.TextField(verbose_name='Описание')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffer.Position', verbose_name='Должность')),
            ],
            options={
                'verbose_name_plural': ' Сотрудники',
                'verbose_name': 'Сотрудник',
            },
        ),
        migrations.CreateModel(
            name='StafferInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_changed', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('date_of_employment', models.DateField(blank=True, null=True, verbose_name='Дата приема на работу')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Неизвестно'), (1, 'Мужской'), (2, 'Женский')], default=0, verbose_name='Пол')),
                ('passport_data', models.TextField(blank=True, null=True, verbose_name='Паспортные данные')),
                ('iin', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ИИН')),
                ('staffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffer.Staffer', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name_plural': 'Дополнительные информации',
                'verbose_name': 'Дополнительная информация',
            },
        ),
    ]
