# Generated by Django 2.0.4 on 2018-05-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['id'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
    ]
