# Generated by Django 2.0.4 on 2018-04-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_changed', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('zip_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Индекс')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('web_site', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт')),
                ('timetable', models.CharField(blank=True, max_length=255, null=True, verbose_name='График работы')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_changed', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('full_name', models.CharField(max_length=255, verbose_name='Название салона')),
                ('city', models.PositiveSmallIntegerField(choices=[(0, 'Астана'), (1, 'Aлматы'), (2, 'Семей')], default=0, verbose_name='Город')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='salon', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
    ]
