# Generated by Django 2.0.4 on 2018-04-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('salon', '0004_auto_20180424_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='service_categories',
            field=models.ManyToManyField(blank=True, related_name='service_category', to='services.Category', verbose_name='Категории'),
        ),
    ]
