# Generated by Django 2.0.4 on 2018-04-24 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_salon_service_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salon',
            old_name='service',
            new_name='services',
        ),
    ]
